version: '3.7'
services:
  web:
    build:
      context: .
      target: 'develop-stage'
    ports:
     - "8080:8080"
    volumes:
      - '.:/movies-frontend'
    command: /bin/sh -c "yarn && quasar dev"